'use strict';

const initDrink = function (DaBot) {
    const name  = 'drink';
    const help  = [
        '======================',
        '==   Drink  Help    ==',
        '======================',
        'Gives you or someone else drink.',
        'Usage: ' + DaBot.config.app.triggerPrefix + 'drink',
        '       ' + DaBot.config.app.triggerPrefix + 'drink TheDude'
    ];
    const picks = [
        '151 Swizzle',
        '7 & 7',
        '75 Cocktail',
        'Absinthe Frappe',
        'Absinthe Suissesse',
        'Acapulco',
        'Acapulco gold',
        'Ace Of Clubs',
        'Adios Motherfucker',
        'Admiral Schley',
        'Affinity',
        'African Punch',
        'Air Mail',
        'Alabama Slammer',
        'Alabazam',
        'Albermarle Fizz',
        'Alexander',
        'Alexanders',
        'Algarrobina',
        'Algonquin',
        'Americano',
        'Anatole Special',
        'Ancient Mariner',
        'Andrew Jackson',
        'Angel\'s Tip',
        'Angel\'s Tit',
        'Angels Passion',
        'Appendicitis',
        'Apple Brandy Rickey',
        'Apple Bumboo',
        'Apple Jack Cocktail',
        'Apple Martini',
        'Applejack Fix',
        'Applejack Highball',
        'Applejack Sour',
        'Arrack Cooler',
        'Arrack Punch',
        'Astro Aku Aku',
        'Astronaut',
        'Aviation',
        'Azteca',
        'B-52',
        'Baby Kitty',
        'Bacardi Cocktail',
        'Bachelor\'s Dream',
        'Bahama Mama',
        'Bahia',
        'Banana Colada',
        'Banana Daiquiri',
        'Barbary Coast',
        'Batanga',
        'Batida',
        'Batida de Cafe',
        'Batman',
        'Bay Breeze',
        'Bazooka Joe',
        'Beer Buster',
        'Belladonna',
        'Bellini',
        'Belmont Breeze',
        'Bentley',
        'Bertha',
        'Bertita',
        'Between the Sheets',
        'Big Spender',
        'Bishop',
        'Bizzy Izzy',
        'Black and Tan Punch',
        'Black Feather',
        'Black Russian',
        'Black Velvet',
        'Blackberry Julep',
        'Blackjack',
        'Bliz\'s Royal Rickey',
        'Blood and Sand',
        'Bloody Bull',
        'Bloody Caesar',
        'Bloody Mary',
        'Blow Job',
        'Blue Blazer',
        'Blue Hawaii',
        'Blue Hawaiian',
        'Blue Moon',
        'Boating Punch',
        'Boilermaker',
        'Bombay Punch',
        'Bon Soir Highball',
        'Boulevard',
        'Bourbon & Branch',
        'Bramble, The',
        'Brandy & Benedictine',
        'Brandy Alexander',
        'Brandy Crusta',
        'Brandy Flip',
        'Brandy Julep',
        'Brandy Smash',
        'Brave Bull',
        'Bronx',
        'Bubblegum Princess',
        'Buck\'s Fizz',
        'Bullshot',
        'Bumboo',
        'Caipirinha',
        'Caipiroska',
        'Cajun Martini',
        'California Dream',
        'Calimocho',
        'Camerons Kick',
        'Campariano',
        'Canchánchara',
        'Candy Apple',
        'Cape Codder',
        'Carleton Rickey',
        'Champagne Cocktail',
        'Champagne Julep',
        'Chi Chi',
        'Chilcano',
        'Chimayo',
        'Chocolate Martini',
        'Chocolate Mudslide',
        'Ciros Special',
        'Clover Club',
        'Cobra\'s Fang',
        'Coco Loco',
        'Cold Deck',
        'Commodore Cocktail',
        'Coronado Luau Special',
        'Corpse Reviver No.2',
        'Cosmonaut',
        'Cosmopolitan',
        'Cowboy Martini',
        'Cranhammer',
        'Cuba Libre',
        'Cuban Apricot',
        'Cuban Cocktail',
        'Cuban Special',
        'Cugat Conga',
        'Daiquiri',
        'Daisy de Santiago',
        'Dallas Star',
        'Dark and Stormy',
        'Death in Venice',
        'Del Coronado',
        'Demerara Dry Float',
        'Depth Charge',
        'Derby Daiquiri',
        'Dillitini',
        'Dirty Martini',
        'Dirty Mother',
        'Doctor Cocktail',
        'Doctor Funk',
        'Dons Own Planters',
        'Draque',
        'Dry Rob Roy',
        'Dubonnet Cocktail',
        'Duck Fart',
        'Dunlop',
        'Eastern Sour',
        'Egg Nog',
        'El Burro',
        'El Diablo',
        'El Floridita No.1',
        'El Floridita No.2',
        'El Guapo',
        'El Macuá',
        'El Presidente',
        'Elizabeth my dear',
        'Embury Daiquiris',
        'Enzoni',
        'Ernest Hemingway Special',
        'Fade to Black',
        'Fellini',
        'Fireball',
        'Fitzgerald',
        'Fjellbekk',
        'Flaming Homer',
        'Floridita Especial',
        'Florodora',
        'Fog Cutter',
        'Fog Horn',
        'Freddy Fudpucker',
        'French 75',
        'French Connection',
        'French Martini',
        'Frenchmans Punch',
        'Frosty Dawn',
        'Fuego Manzana',
        'Fuzzy Navel',
        'Game Over',
        'Gibson',
        'Gimlet',
        'Gin & Tonic',
        'Gin Fix',
        'Gin Fizz',
        'Gin Gin Mule',
        'Gin Julep',
        'Gin Rickey',
        'Gin Sling',
        'Gin Swizzle',
        'Gin Twist',
        'Godfather',
        'Godmother',
        'Golden Cadillac',
        'Golden Dream',
        'Golden Wave',
        'Goombay smash',
        'Granatka',
        'Grapefruit Mojito',
        'Grappa Mojito',
        'Grappacino',
        'Grasshopper',
        'Greyhound',
        'Grog',
        'Grotto Fizz',
        'Hairy Navel',
        'Happy Japa',
        'Harvey Wallbanger',
        'Havana Side-car',
        'Hawaiian',
        'Hawaiian King',
        'Headless horseman',
        'Holland\'s Pride',
        'Honey Bee',
        'Hong Kong Fuey',
        'Honi Honi',
        'Horses Collar',
        'Horses Neck',
        'Hot Pants',
        'Hurricane',
        'Ibsen',
        'Ice Cream Flip',
        'Ice Temple',
        'Imperial Arrack Punch',
        'Imperial Topaz',
        'Irish Coffee',
        'Irish Rickey',
        'Island Temple',
        'Jack Rose',
        'Jagerbomb',
        'Jai Alai Special',
        'Jamestown Julep',
        'Japanese Fizz',
        'Japanese Slipper',
        'Jasmine',
        'Jazz Cocktail',
        'Jersey Girl',
        'Jersey Lightning',
        'Jet Pilot',
        'Joe Buck',
        'John Collins',
        'Jolly Roger',
        'Julip',
        'Junior',
        'Jupiter Cocktail',
        'Kamikaze',
        'Karamelka',
        'Kentucky Mint Julep',
        'Kick in the Pants',
        'King Kong',
        'Kir',
        'Kir Royale',
        'Knickerbocker',
        'Larchmont',
        'Last Word',
        'Lava Lamp',
        'Le Demon Vert',
        'Lemon Coconut Colada',
        'Lemon Drop',
        'Lemon Drop Martini',
        'Lemony Snicket',
        'Long Island Iced Tea',
        'Lord Jim',
        'Love Supreme',
        'Lovely Lovely',
        'Luchador',
        'Lucien Gaudin',
        'Lynchburg Lemonade',
        'MacArthur Cocktail',
        'Madras',
        'Maharaja’s Revenge',
        'Mahukona',
        'Mai Tai',
        'Mamie Taylor',
        'Manhattan',
        'Maple Leaf',
        'Mar Tai',
        'Marble',
        'Margarita',
        'Marguerite Cocktail',
        'Martinez',
        'Martini Cocktail',
        'Mary Pickford',
        'Matador',
        'Melon Ball',
        'Mexican Flag',
        'Micronesian Fizz',
        'Midori Sour',
        'Milk Punch',
        'Millionaire\'s Manhattan',
        'Mimosa',
        'Mint Julep',
        'Mirage Cocktail',
        'Missionary\'s Downfall',
        'Mitch Martini',
        'Mojito',
        'Mojito Colada Royale',
        'Mojito Criollo',
        'Monkey Gland',
        'Mont Blanc',
        'Montgomery',
        'Moonkist Coconut',
        'Morning Glory Fizz',
        'Morretano',
        'Moscow Mule',
        'Mr. Bali Hai',
        'Mr. John Ringling North',
        'Mudslide',
        'Mulata',
        'Mystery Gardenia',
        'Mystery Island',
        'Nautilus',
        'Navy Grog',
        'Negroni',
        'No Job',
        'Nordic Dame',
        'Norsk Mulata',
        'Norwegian Side-car',
        'Nui Nui',
        'Nuremburg Punch',
        'Nutty Colada',
        'Old Cuban',
        'Old Fashioned',
        'Orgasm',
        'Outrigger Special',
        'Overall Julep',
        'Painkiller',
        'Paloma',
        'Papa Dobles',
        'Paradise Cocktail',
        'Peach Punch',
        'Pearl Diver\'s Punch',
        'Pegu Club Cocktail',
        'Penang Afrididi',
        'Pennsylvanian',
        'Periodista',
        'Petit Punch',
        'Pi Yi',
        'Picador',
        'Picon Punch',
        'Pimm\'s Cup',
        'Pina Colada',
        'Pina Sorpresa',
        'Pineapple Mojito',
        'Pink Gin',
        'Pink Lady',
        'Pink Lemonade',
        'Pink Squirrel',
        'Pinky Gonzalez',
        'Pisco Punch',
        'Pisco Sour',
        'Piscola',
        'Planters Punch',
        'Polish Martini',
        'Port Light',
        'Porto Flip',
        'Prairie Oyster',
        'Presbyterian',
        'Puka Punch',
        'Punch of the Legionnaire',
        'Pushka',
        'Q.B. Cooler',
        'Queen\'s Park Swizzle',
        'Raffaello',
        'Ramos Gin Fizz',
        'Raspberry Beret',
        'Recipe Challenge 2006',
        'Red Admiral',
        'Red Cup',
        'Red Snapper',
        'Remsen Cooler',
        'Reverb Crash, The',
        'Rob Roy',
        'Rose',
        'Roy Rogers',
        'Royal Bermuda Yacht Club Cocktail',
        'Royal Romance',
        'Ruby Fizz',
        'Rum Keg',
        'Rum Punch',
        'Rum Rickey',
        'Rum Runner',
        'Rum Sling',
        'Rum Swizzle',
        'Rum Welcome',
        'Russian Spring Punch',
        'Rusty Nail',
        'Salty Dog',
        'San Diego Cocktail',
        'Sangaree',
        'Sangria',
        'Santiago Julep',
        'Satans Whiskers',
        'Sazerac',
        'Scorpion',
        'Scorpion Bowl',
        'Scotch & Soda',
        'Screaming Orgasm',
        'Screwdriver',
        'Seabreeze',
        'Seelbach Cocktail',
        'September Morn',
        'Sex on the Beach',
        'Sexy Woody',
        'Shanghai Buck',
        'Shannon\'s Milk Shake',
        'Sherry Cobbler',
        'Shirley Temple',
        'Side-car',
        'Silk Panties',
        'Silver Bullet',
        'Silver Streak',
        'Singapore Sling',
        'Sloe Comfy Screw',
        'Sloe Comfy Screw Against The Wall',
        'Sloe Gin Fizz',
        'Sloe Screw',
        'Smurf bomb',
        'Sneaky Tiki',
        'Snood Murdekin',
        'Southampton',
        'Southern Cross',
        'Southside',
        'St Lawrence',
        'Star Cocktail',
        'Starboard Light',
        'Staten Island Ferry',
        'Stinger',
        'Stone Fence',
        'Strawberry Margarita',
        'Strawberry Nirvana',
        'Suffering Bastard',
        'Suffering Bastard - Trader Vic\'s',
        'Suzdal Mule',
        'Swamp Zombie',
        'Tahitian',
        'Tapa Punch',
        'Tequila Cocktail',
        'Tequila Daisy',
        'Tequila Mockingbird',
        'Tequila Screwdriver',
        'Tequila Side-car',
        'Tequila Sour',
        'Tequila Sunrise',
        'Tequini',
        'Test Pilot',
        'The Emiliano Zapata Cocktail',
        'The Hearst',
        'Three Dots and a Dash',
        'Thug Passion',
        'Toddy',
        'Tom and Jerry',
        'Tom Collins',
        'Tonga Punch',
        'Toreador',
        'Trader Vic\'s Grog',
        'Treacle, The',
        'Tropical Itch',
        'Turf Cocktail',
        'Twentieth Century Cocktail',
        'Union Jack Cocktail',
        'United Service Punch',
        'Vampiro',
        'Vesper',
        'Vieux Carre',
        'Vit 75',
        'Vodka Collins',
        'Vodka Daisy',
        'Vodka Espresso',
        'Vodka Gimlet',
        'Vodka Martini',
        'Vodka Side-car',
        'Volcano',
        'Ward Eight',
        'West Indies Punch',
        'West Side Cocktail',
        'Whiskey Cobbler',
        'Whiskey Daisey',
        'Whiskey Sling',
        'Whiskey Smash',
        'Whiskey Sour',
        'White Lady',
        'White Lion',
        'White Russian',
        'White Star Imperial Daisy',
        'White Wine Punch',
        'Wibble, The',
        'Woo Woo',
        'Xeres Cocktail',
        'Yungueño',
        'Zombie'
    ];
    DaBot.help.DaBot.push(DaBot.config.app.triggerPrefix + 'drink: Get/Give a drink.');
    DaBot.help.drink = help;

    DaBot.cmds.drink = function (to, args, orig) {
        var drink = picks[Math.floor(Math.random() * (picks.length - 1))];

        if (/^[aeiou](.*)/i.test(drink))
        {
            drink = 'an ' + drink;
        }
        else if(/^the (.*)/i.test(drink))
        {
        }
        else
        {
            drink = 'a ' + drink;
        }

        if (args.length < 1)
        {
            var drinker = (orig.args[0].hasOwnProperty('u')) ? orig.args[0].u.username : orig.args[0].title;
            DaBot.say(to, '_ hands ' + drinker + ' ' + drink + ' _');
        }
        else
        {
            DaBot.say(to, '_ hands @' + args[0] + ' ' + drink + ' _');
        }
    }
};

module.exports = initDrink;